# Generated by Django 3.2.8 on 2021-11-04 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='zbdoor_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('payload', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('battery', models.IntegerField()),
            ],
        ),
    ]
