# Generated by Django 3.2.8 on 2021-11-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zbdoor_1',
            name='battery_low',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='zbdoor_1',
            name='contact',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='zbdoor_1',
            name='linkquality',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='zbdoor_1',
            name='voltage',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='zbdoor_1',
            name='battery',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='zbdoor_1',
            name='payload',
            field=models.TextField(default=None),
        ),
    ]
