# Generated by Django 3.2.8 on 2021-11-04 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20211104_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='zbbtn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('battery', models.IntegerField(default=None)),
                ('battery_low', models.BooleanField(default=None)),
                ('action', models.CharField(default=None, max_length=10)),
                ('linkquality', models.IntegerField(default=None)),
                ('voltage', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='zbdoor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('battery', models.IntegerField(default=None)),
                ('battery_low', models.BooleanField(default=None)),
                ('contact', models.BooleanField(default=None)),
                ('linkquality', models.IntegerField(default=None)),
                ('voltage', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='zbtmphum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('battery', models.IntegerField(default=None)),
                ('battery_low', models.BooleanField(default=None)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('linkquality', models.IntegerField(default=None)),
                ('voltage', models.IntegerField(default=None)),
            ],
        ),
        migrations.DeleteModel(
            name='zbdoor_1',
        ),
    ]
