# Generated by Django 3.2.8 on 2021-11-04 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20211104_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zbbtn',
            name='battery_low',
        ),
        migrations.RemoveField(
            model_name='zbtmphum',
            name='battery_low',
        ),
    ]
